export const DATA = {
  nav: [
    { label: "Academy", trustLabel: "Talent Programmes", page: "academy" },
    { label: "Marketing", trustLabel: "Digital Solutions", page: "marketing" },
    { label: "Labs", trustLabel: "Product Studio", page: "labs" },
    { label: "Proof", trustLabel: "Delivery Proof", page: "customers" },
    { label: "Contact", trustLabel: "Enquiry", page: "contact" },
  ],
  gateway: {
    neo: {
      kicker: "For teams that move before the market catches up.",
      title: "Loud, fast, fluorescent. The Nexara you'd screenshot for your story.",
      body: "Live cohorts, campaigns that hit, and AI systems that actually ship, from one team that treats every brief like launch week.",
      chips: ["no cap", "shipping daily", "vibes reserved"],
      cta: "Enter the Chaos",
    },
    trust: {
      kicker: "Three specialist forces. One governance standard.",
      title: "Capability you can put your name to.",
      body: "Academy builds talent, Digital builds market infrastructure, Labs builds applied AI. Every engagement carries a named owner, a written scope, a reporting cadence and a clear data boundary.",
      chips: ["Named owner", "Written scope", "Reported cadence"],
      cta: "Enter the Firm",
    },
  },
  home: {
    neo: {
      eyebrow: "🚀 NEXARA GEN Z",
      title: "We build tomorrow's",
      accent: "internet_",
      body: "Academic programs, AI experiments, software shipping, and marketing that slaps. One studio, three obsessions. Pick your entrance — let's cook.",
      calloutTitle: "Three engines. Zero filler.",
      calloutBody: "Pick the track that hits your problem now. Then stack Academy, Digital Marketing and Labs together when the project needs people, presence, and systems all firing at once.",
    },
    trust: {
      eyebrow: "NEXARA ENTERPRISE",
      title: "Three forces. One standard.",
      accent: "Academy · Digital · Labs.",
      body: "Talent enablement, digital market infrastructure and applied AI — run as three specialist disciplines, each held to the same governance bar: named owner, written scope, reporting cadence, evidence and data discipline.",
      calloutTitle: "Depth in each line. One accountable operating model across all three.",
      calloutBody: "Each division goes deep in its own discipline. What they share is the standard — scoped delivery, outcome reporting, verified claims and defined data boundaries on every engagement.",
    },
  },
  unbox: {
    neo: {
      eyebrow: "// UNBOX NEXARA",
      title: "Three engines. One operating core.",
      body: "Scroll through the gateway layer and see how Academy, Digital Marketing and Labs combine into one delivery model for growth-city teams.",
      sequence: "NEXARA CORE",
    },
    trust: {
      eyebrow: "Operating model",
      title: "Specialist depth, governed the same way.",
      body: "Each division owns its discipline end to end. The shared spine connects them — scoping, reporting, controls and production-readiness applied identically across talent, digital and AI.",
      sequence: "One governance standard",
    },
    faces: [
      { label: "Talent Programmes", sub: "Academy capability", section: "academy", color: "var(--unbox-academy)" },
      { label: "Digital Solutions", sub: "Market systems", section: "marketing", color: "var(--unbox-marketing)" },
      { label: "AI & Automation", sub: "Applied AI systems", section: "labs", color: "var(--unbox-labs)" },
      { label: "Scope", sub: "Scoped intake", section: "contact", color: "var(--unbox-briefs)" },
      { label: "Cities", sub: "Growth context", section: "home", color: "var(--unbox-cities)" },
      { label: "Standards", sub: "Delivery control", section: "company", color: "var(--unbox-standards)" },
    ],
    signals: [
      ["Talent", "cohorts, portfolios, placement readiness"],
      ["Digital", "positioning, websites, content, demand"],
      ["AI", "workflow discovery, AI systems, guardrails"],
      ["Core", "scoping, reporting, operating readiness"],
    ],
  },
  market: {
    title: {
      neo: "Built for growth cities that never sleep.",
      trust: "Built for India's growth markets.",
    },
    body: {
      neo: "Nexara is tuned for places where talent is hungry, local brands are digitizing fast, and AI adoption is just getting real.",
      trust: "The firm operates where it can demonstrate results: Indian growth cities where skilling demand, regional brand-building and operational digitization are all moving at once.",
    },
    cities: ["Visakhapatnam", "Vijayawada", "Coimbatore", "Indore", "Nagpur", "Surat", "Mysuru", "Bhubaneswar"],
    assumptions: [
      "Students and freshers need employable portfolios, English communication support and interview readiness.",
      "SMBs and regional brands need affordable brand, web, social and lead-generation systems.",
      "Hospitals, institutes, real estate, logistics and service businesses need practical automation before advanced AI.",
      "Buyers prefer clear packages, visible deliverables, local proof and WhatsApp-friendly enquiry flows.",
    ],
  },
  superSkills: [
    {
      title: "City Launch Stack",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Train the local crew, launch the brand, wire the follow-up — all before competitors finish their morning meeting.",
      trust: "Enter a new city with one scoped engagement: trained local hires, a launched market presence and follow-up automation, governed under a single owner.",
      stack: ["Hiring pipeline", "Launch website", "Lead capture", "AI follow-up"],
    },
    {
      title: "Placement Growth Loop",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Turn learner wins into proof, proof into demand, demand into better hiring loops. The flywheel is real.",
      trust: "Cohort scores feed employer requirements, outcomes become documented proof, and proof feeds the next hiring cycle — one reported loop from training to placement.",
      stack: ["Cohort scoring", "Employer requirements", "Outcome stories", "Placement dashboard"],
    },
    {
      title: "AI-Ready Business Kit",
      sections: ["Digital Marketing", "Labs"],
      neo: "Give regional brands the website, data trail and automation layer they need before the AI wave lands. No more catching up.",
      trust: "Get the web presence, structured knowledge base and first automation layer in place — the foundation an AI rollout needs before it can survive real traffic.",
      stack: ["Service pages", "Knowledge base", "Document AI", "Workflow audit"],
    },
    {
      title: "Founder Visibility Engine",
      sections: ["Digital Marketing", "Labs"],
      neo: "Get the founder visible, sharpen the offer, make every inbound easy to chase. Stop hiding the best product in the room.",
      trust: "Sharpen the founder's positioning, run a documented content cadence, capture enquiries and route them CRM-ready — so inbound interest becomes a tracked pipeline.",
      stack: ["Positioning", "Content system", "Landing pages", "Lead routing"],
    },
    {
      title: "Institution Outcome OS",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Make colleges look outcome-first with training, reporting and placement proof that actually moves.",
      trust: "Give the institution a reported operating layer: training tracks, progress reporting, demo days and placement analytics the placement cell can stand behind.",
      stack: ["Training tracks", "Progress reports", "Demo days", "Placement analytics"],
    },
  ],
  sections: {
    academy: {
      id: "academy",
      index: "01",
      name: "Academy",
      short: { neo: "Learn fast. Build proof. Get placed. Receipts included.", trust: "Talent built cohort by cohort, with reported placement readiness." },
      statement: "Talent isn't found — it's built. Cohort by cohort, project by project, until the portfolio speaks before the résumé does.",
      hero: {
        neo: {
          eyebrow: "🎓 NEXARA ACADEMY",
          title: "Skills that hit different.",
          accent: "Train. Build. Show.",
          body: "Live cohorts, real projects, mentor reviews and portfolio prep for learners who are done collecting certificates and ready to ship actual work.",
          primary: "See the tracks",
          secondary: "Placement proof",
        },
        trust: {
          eyebrow: "Talent Programmes",
          title: "Talent built until the portfolio speaks first.",
          accent: "Map → Cohort → Proof → Place.",
          body: "Academy runs cohort-based training, portfolio assessment, managed internships and placement-readiness — each cohort scoped, scored and reported, for students, institutions and employers alike.",
          primary: "Plan an Academy programme",
          secondary: "See the placement workflow",
        },
      },
      stats: [["6", "skill options"], ["3", "audience groups"], ["4", "delivery stages"], ["3", "programme packages"]],
      modules: [
        { title: "Career Tracks", neo: "Full-stack, AI, design and growth — sprint-based builds that turn learners into people worth hiring.", trust: "Role-aligned tracks across engineering, data, design, cloud and growth — each mapped to a hiring signal, not a syllabus." },
        { title: "Internship Engine", neo: "Real projects, mentor pressure and weekly output. Move like a junior operator from week one.", trust: "Managed internships with assigned mentors, weekly delivery checkpoints and portfolio artifacts on the record." },
        { title: "Placement Desk", neo: "Profile polish, mock interviews and partner matching — none of the generic placement-office theater.", trust: "Employer requirements, candidate screening, interview readiness and offer-stage tracking — owner and pipeline named." },
        { title: "Campus Programmes", neo: "Turn classrooms into launch rooms. Dashboards students actually care about using.", trust: "Institution programmes with cohort reporting, outcomes tracking and a clear governance owner for the placement cell." },
      ],
      stack: ["Full-Stack Engineering", "Data & AI", "Product Design", "Cloud & DevOps", "Growth Marketing", "Portfolio Reviews"],
      audiences: [
        { title: "Students", neo: "For freshers who need an employable portfolio that stands out — not another PDF nobody reads.", trust: "Freshers who need a portfolio that proves capability — applied projects, communication readiness and interview prep, built to a plan." },
        { title: "Colleges", neo: "Give students a launch system that feels current. Make the placement cell proud.", trust: "Institutions that need internship structure, cohort reporting and hiring-partner alignment they can report on to leadership." },
        { title: "Employers", neo: "Meet junior talent that has already shipped production code before the first call. No dry runs.", trust: "Regional IT firms, agencies and growing companies that need screened, project-tested entry-level candidates against a written role brief." },
      ],
      stackDetails: [
        { title: "Full-Stack Engineering", outcome: "Deployable apps", deliverables: ["React interfaces", "API foundations", "Database basics", "Deployment workflow"] },
        { title: "Data & AI", outcome: "Analytical projects", deliverables: ["Data cleaning", "Dashboards", "Model basics", "AI use cases"] },
        { title: "Product Design", outcome: "Portfolio-ready UX", deliverables: ["User flows", "Wireframes", "UI systems", "Case studies"] },
        { title: "Cloud & DevOps", outcome: "Operational fluency", deliverables: ["Git workflow", "Hosting", "CI basics", "Monitoring"] },
        { title: "Growth Marketing", outcome: "Campaign literacy", deliverables: ["Funnels", "Landing pages", "Content tests", "Reporting"] },
        { title: "Portfolio Reviews", outcome: "Hiring proof", deliverables: ["Project audits", "Resume review", "Mock interviews", "Profile polish"] },
      ],
      process: [
        { step: "01", title: "Map the learner", body: "Assess current skill level, target roles and portfolio gaps." },
        { step: "02", title: "Run the cohort", body: "Live sessions, project sprints, mentor reviews and weekly delivery." },
        { step: "03", title: "Build proof", body: "Turn projects into case studies, demos and interview-ready narratives." },
        { step: "04", title: "Place or partner", body: "Match candidates to interviews or report cohort outcomes." },
      ],
      packages: [
        { name: "Career Cohort", fit: "Students and freshers", price: "Priced per cohort and city", duration: "Set by track length", includes: ["Facilitated cohort sessions", "Project portfolio", "Mentor reviews", "Placement prep"] },
        { name: "Internship Batch", fit: "Colleges and academies", price: "Priced per batch size", duration: "Aligned to the academic calendar", includes: ["Managed internship", "Weekly reports", "Completion scoring", "Demo day"] },
        { name: "Hiring Pipeline", fit: "Employers", price: "Custom, role-based", duration: "Runs until roles close", includes: ["Role requirements", "Candidate screening", "Interview shortlist", "Offer tracking"] },
      ],
      faqs: [
        ["Is Academy only for students?", "No. Academy supports learner cohorts, college programmes and employer-led hiring pipelines, with scope adjusted for each audience."],
        ["Do you guarantee placement?", "Nexara provides placement preparation, portfolio support and hiring coordination where included in scope. Nexara does not publish a general placement guarantee; any hiring commitment must be separately scoped and documented."],
        ["How is the Academy programme structured compared to standard skilling courses?", "The programme is built around applied projects, mentor review, communication readiness and portfolio proof rather than passive course completion."],
      ],
      intake: { primary: "Plan an Academy programme", secondary: "Tell us the city, learner count, target roles, timeline and placement expectations. We return a scoped programme with a named owner." },
      subpages: [
        {
          slug: "tracks",
          title: "Tracks",
          callout: { neo: "Pick a lane, build proof, stop sounding entry-level. The glow-up starts here.", trust: "Each track maps to a hiring signal and ends in a measurable skill outcome." },
          cards: [
            { title: "Full-stack sprint", neo: "Ship interfaces, APIs and deployable flows. Real output, not slides.", trust: "Frontend, backend and deployment foundations — output is a deployed app, not a certificate." },
            { title: "AI/data sprint", neo: "Go from notebooks to useful models and dashboards fast.", trust: "Data workflows, AI foundations and a delivered analytical project." },
            { title: "Design studio", neo: "Build product taste, UX logic and portfolio screens worth showing.", trust: "UX, interface design and product presentation, reviewed against hiring standards." },
            { title: "Cloud operations", neo: "Learn the infra moves teams expect on day one. No excuses.", trust: "Cloud, DevOps and operational basics for the junior technical roles teams actually open." },
          ],
        },
        {
          slug: "internships",
          title: "Internships",
          callout: { neo: "Internships that feel like a real tech squad — not a certificate farm.", trust: "A managed bridge from learning to workplace delivery, with a checkpoint every week." },
          cards: [
            { title: "Mentor pods", neo: "Small groups, direct feedback, no hiding. This is peak learning.", trust: "Each pod has an assigned mentor owning weekly progress and quality review." },
            { title: "Weekly reviews", neo: "Every week ends with a live demo, a score and next moves.", trust: "Every week closes with a demo, a score and named next steps — progress on the record." },
            { title: "Client-style projects", neo: "Work on prompts that feel like actual business problems. Because they are.", trust: "Project scopes match professional delivery expectations, not classroom exercises." },
            { title: "Completion reports", neo: "Leave with proof that says what you can actually build.", trust: "Final reports document capability, participation and project quality — proof an employer can read." },
          ],
        },
        {
          slug: "placements",
          title: "Placements",
          callout: { neo: "Get good, get seen, get hired. That's the whole playbook.", trust: "Hiring-partner workflows run inside the programme, not after it. Preparation, not a guarantee." },
          cards: [
            { title: "Interview prep", neo: "Practice until your answers stop sounding rehearsed.", trust: "Structured preparation for technical and behavioral interviews, scored before the real one." },
            { title: "Partner matching", neo: "Match skills to teams that actually need them. No spray and pray.", trust: "Candidate profiles matched against the employer's written role requirements." },
            { title: "Offer tracking", neo: "Know where every application stands. No black holes.", trust: "Pipeline visibility from shortlist to interview to offer — every candidate accounted for." },
            { title: "Alumni proof", neo: "Show the next cohort what the path looks like. Real receipts.", trust: "Documented outcomes that support institutional and employer confidence — approved before they're published." },
          ],
        },
      ],
      proof: [
        { name: "Learner cohort", result: { neo: "Portfolio proof built for interviews, not a folder nobody opens", trust: "Applied projects converted into review-ready portfolios, scored against hiring criteria" }, org: "Academy programme" },
        { name: "College batch", result: { neo: "Internship rhythm made visible — weekly, scored, no guesswork", trust: "Weekly reporting and completion scoring put on the record for the placement cell" }, org: "Institution programme" },
        { name: "Employer shortlist", result: { neo: "Screened profiles, less hiring theater", trust: "Role-fit screening and interview prep delivered against a written hiring brief" }, org: "Hiring support" },
      ],
    },
    marketing: {
      id: "marketing",
      index: "02",
      name: "Digital Marketing",
      short: { neo: "Make the brand impossible to ignore. Full stop.", trust: "Market infrastructure: positioning, build, launch, optimize." },
      statement: "Attention is earned in the first ten seconds. Everything we build is engineered for that moment — and the decision that follows it.",
      hero: {
        neo: {
          eyebrow: "📣 NEXARA DIGITAL MARKETING",
          title: "We make the internet care.",
          accent: "get loud, stay loud.",
          body: "Positioning, websites, content systems and campaign loops built to convert. We put your offer in front of the people who actually matter — and keep it there.",
          primary: "See the growth stack",
          secondary: "Brand proof",
        },
        trust: {
          eyebrow: "Digital Solutions",
          title: "Market infrastructure that earns its first ten seconds.",
          accent: "Position → Build → Launch → Optimize.",
          body: "Digital delivers brand identity, websites, content operations, SEO foundations and performance campaigns as one system — every asset scoped, shipped to a deliverable and reported on a cadence.",
          primary: "Map a marketing system",
          secondary: "See documented outcomes",
        },
      },
      stats: [["6", "growth services"], ["4", "launch stages"], ["3", "channel layers"], ["3", "engagement packages"]],
      modules: [
        { title: "Brand Identity", neo: "Names, visuals and voice that don't look like a Canva template pack. Custom attitude only.", trust: "Naming, visual system, messaging and launch kit — documented brand governance, not a one-off logo." },
        { title: "Web Experience", neo: "Pages that sell before users bounce. Your site should be your best closer.", trust: "Corporate sites, landing pages and product pages built around a defined conversion path." },
        { title: "Social Studio", neo: "Content with taste, tempo and output that doesn't dry up. Stop the generic spam.", trust: "Always-on content for LinkedIn, Instagram, YouTube and community channels, run on a published calendar." },
        { title: "Performance Growth", neo: "Ads, SEO and reporting loops where the spend explains itself. Zero fluff.", trust: "Paid media, SEO and analytics with a reporting cadence that explains where every rupee went." },
      ],
      stack: ["Brand Systems", "Websites", "Social Media", "Performance Ads", "SEO", "Content Studio"],
      audiences: [
        { title: "Founders", neo: "For builders in growth cities who need people to get the offer in under ten seconds.", trust: "Founder-led companies that need positioning, a site that converts and launch assets they can stand behind." },
        { title: "Growing Brands", neo: "For local leaders and service brands leaking attention across every channel. Fix the leaks.", trust: "Regional businesses that need consistent brand, content and acquisition run as one execution system." },
        { title: "Enterprise Teams", neo: "For multi-branch teams drowning in campaign chaos. One system, one rhythm.", trust: "Multi-branch teams that need governed, repeatable campaign operations with reporting leadership can read." },
      ],
      stackDetails: [
        { title: "Brand Systems", outcome: "Clear identity", deliverables: ["Positioning", "Visual system", "Messaging", "Launch kit"] },
        { title: "Websites", outcome: "Conversion-ready presence", deliverables: ["Site map", "UX sections", "Copy hierarchy", "Responsive build"] },
        { title: "Social Media", outcome: "Consistent visibility", deliverables: ["Content pillars", "Calendar", "Creative formats", "Publishing rhythm"] },
        { title: "Performance Ads", outcome: "Measured acquisition", deliverables: ["Campaign setup", "Creative tests", "Audience map", "Weekly reporting"] },
        { title: "SEO", outcome: "Search foundation", deliverables: ["Metadata", "Page structure", "Internal links", "Content plans"] },
        { title: "Content Studio", outcome: "Reusable assets", deliverables: ["Posts", "Carousels", "Short scripts", "Campaign copy"] },
      ],
      process: [
        { step: "01", title: "Position", body: "Clarify audience, category, offer and proof before design starts." },
        { step: "02", title: "Build assets", body: "Create brand, website, content and campaign assets as one system." },
        { step: "03", title: "Launch channels", body: "Publish the site, activate content and run performance campaigns." },
        { step: "04", title: "Optimize", body: "Review reporting, test creative, improve pages and compound winners." },
      ],
      packages: [
        { name: "Brand Launch", fit: "New or repositioning brands", price: "Priced per identity scope", duration: "Confirmed at kickoff", includes: ["Positioning", "Identity", "Messaging", "Launch assets"] },
        { name: "Website Growth", fit: "Companies with weak conversion", price: "Priced per site architecture", duration: "Set by page count and content readiness", includes: ["Site architecture", "Copy", "Design", "SEO foundations"] },
        { name: "Demand System", fit: "Teams ready to scale", price: "Monthly retainer, scoped to budget", duration: "Rolling, cadence agreed in scope", includes: ["Content calendar", "Paid campaigns", "Reporting", "Creative testing"] },
      ],
      faqs: [
        ["Do you only design websites?", "No. Website work can be delivered independently, but it is usually strongest when connected to positioning, content and lead-capture strategy."],
        ["Can Nexara run ongoing marketing?", "Yes. Nexara can support launch projects, monthly content operations and performance campaigns depending on scope and budget."],
        ["What do you need before starting?", "Nexara requires a defined offer, target audience, existing channel inventory, current website or creative assets, an approximate budget range, and a stated primary business objective before scoping begins."],
      ],
      intake: { primary: "Map a marketing system", secondary: "Tell us the city, category, offer, current website, channels and primary growth goal. We return a scoped system with deliverables and a reporting cadence." },
      subpages: [
        {
          slug: "brand",
          title: "Brand",
          callout: { neo: "Look sharp enough to get saved and shared. Custom details only, no template packs.", trust: "One identity system, documented — so the brand reads the same on every touchpoint." },
          cards: [
            { title: "Positioning", neo: "Say what you are before the market decides for you.", trust: "Category, audience and value proposition defined and written down before design begins." },
            { title: "Visual identity", neo: "Logo, color, type — built with actual custom attitude, not vibes-as-a-service.", trust: "A visual system usable across every digital and sales touchpoint, with usage rules." },
            { title: "Messaging", neo: "Copy that sounds like a company with a real pulse.", trust: "Messaging pillars that keep website, sales and campaign communication consistent." },
            { title: "Launch kits", neo: "Everything needed to go live without the last-minute scramble.", trust: "Brand assets, templates and rollout guidance handed to the launch team, ready to use." },
          ],
        },
        {
          slug: "web",
          title: "Web",
          callout: { neo: "Your website should be your best closer. Bounce rate is not a personality.", trust: "Sites built to explain the offer, move the visitor to one action and stand up to real traffic." },
          cards: [
            { title: "Landing pages", neo: "Fast, focused, one offer and one action. Nothing else.", trust: "Campaign pages with one offer, one action and a measured conversion path." },
            { title: "Corporate sites", neo: "A full website that feels alive — not an archived press kit.", trust: "Multi-section sites with service pages, proof and contact flows that route to your pipeline." },
            { title: "Product pages", neo: "Show the thing, explain the win, kill the doubt.", trust: "Product pages that lead with the outcome, then the features, then the buyer's reassurance." },
            { title: "SEO foundations", neo: "Make the site findable without making it boring.", trust: "Metadata, heading structure, internal links and a content plan the site can be found on." },
          ],
        },
        {
          slug: "growth",
          title: "Growth",
          callout: { neo: "Campaigns that move actual numbers — not just deck slides.", trust: "Campaigns run with defined measurement, a reporting cadence and a documented optimization loop." },
          cards: [
            { title: "Paid acquisition", neo: "Creative tests, budget discipline and hooks that earn the click.", trust: "Paid campaigns built around named audiences, a clear offer and weekly reporting." },
            { title: "Reporting", neo: "Dashboards people can read without a translator.", trust: "Weekly and monthly reports tied to pipeline and performance, not vanity metrics." },
            { title: "Retargeting", neo: "Bring back the warm audience before they forget you existed.", trust: "Retargeting sequenced by behavior, funnel stage and intent." },
            { title: "Creative testing", neo: "Ship variants fast, kill the losers, compound the winners.", trust: "Controlled tests of message, format and segment — winners kept on evidence, losers cut." },
          ],
        },
      ],
      proof: [
        { name: "Founder-led service brand", result: { neo: "Offer got sharper before the market got to judge it", trust: "Positioning, website architecture and enquiry flow defined and documented" }, org: "Brand and web" },
        { name: "Regional healthcare business", result: { neo: "Content stopped feeling random — pillars, pages, rhythm sorted", trust: "Content pillars, landing pages and a reporting cadence put in place" }, org: "Growth system" },
        { name: "Multi-location business", result: { neo: "Campaigns got a clean rhythm instead of spray-and-pray", trust: "Channel plan and performance review cadence established across locations" }, org: "Campaign operations" },
      ],
    },
    labs: {
      id: "labs",
      index: "03",
      name: "Product Studio",
      short: { neo: "We build the system that solves the problem — SaaS, products, integrations, AI where it fits.", trust: "Software that solves the problem — SaaS, B2B products and integrations, with AI where it earns its place." },
      statement: "Technology is never the point — the problem is. We build the system that solves it: SaaS, B2B products, integrations, and AI only where it earns its place.",
      hero: {
        neo: {
          eyebrow: "🛠️ PRODUCT STUDIO",
          title: "We build the system that solves the problem.",
          accent: "SaaS, products, integrations — AI where it fits.",
          body: "Product Studio turns business problems into working software — SaaS platforms, B2B products, internal tools and the integrations that connect them, with AI and automation added only where they actually earn their place.",
          primary: "See what we build",
          secondary: "Product proof",
        },
        trust: {
          eyebrow: "Product Studio",
          title: "We build the system that solves the problem.",
          accent: "SaaS, B2B products, integrations — AI where it fits.",
          body: "Product Studio designs and ships custom software, SaaS platforms, B2B products and the integrations that tie them together — scoped against a real business problem, with AI and automation applied only where they earn their place, not as the headline.",
          primary: "Scope a build",
          secondary: "See how we build",
        },
      },
      stats: [["4", "delivery pillars"], ["3", "build packages"], ["4", "stage delivery"], ["100%", "problem-scoped"]],
      modules: [
        { title: "Custom Software & SaaS", neo: "Web apps and SaaS built from scratch — architecture to ship, no template traps.", trust: "Web apps and SaaS platforms built from scratch — architecture, product UI and a clear path to ship and scale." },
        { title: "B2B Products & Platforms", neo: "Portals, dashboards and internal platforms that run the actual operation.", trust: "Portals, dashboards and internal platforms that run real business operations — not demos." },
        { title: "Integrations & Systems", neo: "APIs, pipelines and internal tools so your stack finally talks to itself.", trust: "APIs, data pipelines and systems integration so tools, teams and data actually talk to each other." },
        { title: "AI & Automation", neo: "RAG, agents and document AI — added where they earn it, with brakes on.", trust: "RAG, agents and document AI applied where they earn their place — with evaluation, guardrails and human review." },
      ],
      stack: ["Product Architecture", "SaaS Builds", "B2B Platforms", "Integrations", "AI & Automation", "Cloud & DevOps"],
      audiences: [
        { title: "Founders & Startups", neo: "For founders who need a real product built right — MVP to scale, not a throwaway prototype.", trust: "Founders who need a product built right the first time — from MVP to scale, with a clear path forward." },
        { title: "Operations Teams", neo: "For teams buried in manual work and disconnected tools that should be one system.", trust: "Teams stuck with manual work and disconnected tools who need software that actually runs the operation." },
        { title: "Leadership Teams", neo: "For owners who want a scoped build tied to a real outcome — not another deck.", trust: "Decision-makers who want a scoped build with a clear path from business problem to working software." },
      ],
      stackDetails: [
        { title: "Product Architecture", outcome: "Built to scale", deliverables: ["System design", "Data model", "Tech stack", "Scale plan"] },
        { title: "SaaS & Web Apps", outcome: "Shippable product", deliverables: ["Product UI", "Auth & billing", "Core features", "Deploy pipeline"] },
        { title: "B2B Platforms", outcome: "Operational software", deliverables: ["Admin portals", "Dashboards", "Roles & access", "Workflows"] },
        { title: "Integrations", outcome: "Connected systems", deliverables: ["API integrations", "Data sync", "Webhooks", "Internal tools"] },
        { title: "AI & Automation", outcome: "Applied where it fits", deliverables: ["Retrieval / RAG", "Agent workflows", "Document AI", "Guardrails & review"] },
        { title: "Cloud & DevOps", outcome: "Reliable delivery", deliverables: ["Hosting", "CI/CD", "Monitoring", "Security review"] },
      ],
      process: [
        { step: "01", title: "Frame the problem", body: "Start with the business problem and the outcome you need — not the technology." },
        { step: "02", title: "Design the system", body: "Architecture, product scope, data, integrations, and where AI actually helps." },
        { step: "03", title: "Build and prove", body: "Ship in increments, test against real use, and harden what holds." },
        { step: "04", title: "Launch and support", body: "Deploy with monitoring, then iterate — clean handover or ongoing support." },
      ],
      packages: [
        { name: "Discovery Sprint", fit: "Teams scoping a build", price: "Fixed-scope sprint pricing", duration: "Short sprint, dates agreed in scope", includes: ["Problem mapping", "Solution architecture", "Scope & estimate", "Build roadmap"] },
        { name: "Product Build", fit: "Teams ready to ship", price: "Priced per product scope", duration: "Set by build phases", includes: ["Architecture", "Product build", "QA & evaluation", "Production launch"] },
        { name: "Build & Run", fit: "Teams needing ongoing delivery", price: "Retainer scoped to roadmap", duration: "Ongoing, cadence agreed", includes: ["Feature delivery", "Integrations", "AI & automation", "Monitoring & support"] },
      ],
      faqs: [
        ["Do you only build AI products?", "No. We build SaaS, B2B products, internal platforms and integrations. AI and automation are applied where they genuinely help — never forced into a build to look modern."],
        ["Can you build a full product from scratch?", "Yes — from problem framing and architecture through product build, launch and support. MVP to scale, with the right stack for the job."],
        ["What is the first step?", "Every engagement starts by framing the problem and the outcome. We map the solution, scope the build, and agree a roadmap before any development begins."],
      ],
      intake: { primary: "Scope a build", secondary: "Tell us the problem, your current tools, the users and the outcome you need. We return a solution approach, scope and roadmap before any build." },
      subpages: [
        {
          slug: "products",
          title: "Products & SaaS",
          callout: { neo: "SaaS and B2B products built around the real problem — scoped before they ship.", trust: "SaaS platforms and B2B products built around a real business problem — scoped to your case before they ship." },
          cards: [
            { title: "SaaS Platforms", neo: "Multi-tenant products with auth, billing and a path to scale.", trust: "Multi-tenant SaaS with authentication, billing and a clear path to scale." },
            { title: "B2B Products", neo: "Portals and platforms that run real operations, not demos.", trust: "Customer portals and B2B platforms built around live business operations." },
            { title: "Internal Tools", neo: "Dashboards and admin tools that replace the spreadsheet sprawl.", trust: "Dashboards and internal tools that replace manual spreadsheets and ad-hoc processes." },
            { title: "MVP to Scale", neo: "Start lean, prove it, then harden for real traffic.", trust: "Start with a focused MVP, prove it against real use, then harden for scale." },
          ],
        },
        {
          slug: "ai-automation",
          title: "AI & Automation",
          callout: { neo: "AI added where it earns it — grounded, evaluated, with brakes on.", trust: "AI and automation applied where they earn their place — grounded, evaluated and controlled." },
          cards: [
            { title: "Retrieval / RAG", neo: "Grounded answers over your own knowledge, every source traced.", trust: "Grounded retrieval over internal knowledge — every answer cites its source." },
            { title: "Agents", neo: "Agent workflows with scoped tools, logs and brakes built in.", trust: "Agent workflows with scoped tool access, trace logs and evaluation from the start." },
            { title: "Document AI", neo: "Messy docs become structured, reviewable data.", trust: "Extraction and classification for operational documents, with validation before export." },
            { title: "Guardrails", neo: "Evaluations and human review where judgment actually matters.", trust: "Evaluation, guardrails and a human review step on risk-sensitive outputs, by design." },
          ],
        },
        {
          slug: "delivery",
          title: "Build & Delivery",
          callout: { neo: "Scope to launch with the boring parts — hosting, access, monitoring — handled.", trust: "From architecture to launch, with hosting, access control and monitoring settled before go-live." },
          cards: [
            { title: "Architecture", neo: "Pick the stack, data path and integrations before code.", trust: "Solution architecture across stack, data, integrations and security — decided before build." },
            { title: "Build & QA", neo: "Ship in increments, test against real use, harden what holds.", trust: "Iterative development with QA, evaluation and stakeholder demos through the build." },
            { title: "Launch", neo: "Go live with monitoring and a rollback path, not crossed fingers.", trust: "Production launch with monitoring, access controls and a clear rollback path." },
            { title: "Support", neo: "Logs, monitoring and a support loop running after launch.", trust: "Monitoring and a support cadence after launch — handover or ongoing, your call." },
          ],
        },
      ],
      proof: [
        { name: "SaaS platform", result: { neo: "A real product shipped — auth, billing and a path to scale, not a prototype", trust: "Custom SaaS product scoped, built and shipped with auth, billing and a clear path to scale" }, org: "Product build" },
        { name: "B2B operations portal", result: { neo: "Spreadsheets and disconnected tools became one workflow", trust: "Internal B2B platform that replaced manual spreadsheets and disconnected tools with one workflow" }, org: "B2B platform" },
        { name: "AI-assisted workflow", result: { neo: "AI added to the work that repeats — with review where it counts", trust: "Document and knowledge workflow automated with retrieval and a human review step where it counts" }, org: "AI & automation" },
      ],
    },
  },
  customers: [
    { id: "academy", section: "Academy", company: "Learner and college programmes", neo: "Training gets a visible rhythm: projects, reviews, portfolios and interview prep. No more mystery about what the cohort is actually producing.", trust: "Applied projects, mentor checkpoints, weekly reporting and placement-readiness — the cohort's output is on the record, not assumed." },
    { id: "marketing", section: "Digital Marketing", company: "Founder and regional business launches", neo: "The offer gets sharper before the market judges it. One system for brand, web and demand.", trust: "Positioning, site architecture, content and reporting delivered as one documented market-readiness workflow." },
    { id: "labs", section: "Product Studio", company: "SaaS, B2B products and internal platforms", neo: "We build the system that solves the problem — SaaS, products and integrations, with AI where it fits.", trust: "Custom software, SaaS, B2B platforms and integrations — with AI and automation applied where it earns its place." },
  ],
  company: {
    facts: [
      ["Status", "Incorporated capability firm"],
      ["Forces", "Academy, Digital, Labs"],
      ["Standard", "Named owner, written scope, reported cadence"],
      ["Operating region", "India-first growth markets"],
    ],
    standards: [
      { title: "Verified claims", body: "Public numbers, client names and guarantees appear only after evidence and approval. If we can't show it, we don't claim it." },
      { title: "Scoped delivery", body: "Every engagement opens with audience, goals, deliverables, timeline, a named owner and success criteria — in writing." },
      { title: "Data boundaries", body: "Before any Labs build, we settle hosting, access, auditability, human review and risk level." },
      { title: "Outcome reporting", body: "Academy, Digital and Labs each report progress, completion and next steps on an agreed cadence." },
    ],
    neo: {
      manifesto: "Nexara Gen Z is the IT company that doesn't act like one. Academy turns learning into portfolio proof, Digital Marketing turns offers into market signal, and Labs turns AI ideas into working systems — shipping daily across all three.",
      principles: [
        { title: "Keep the three engines loud", body: "Academy, Digital Marketing and Labs each keep their own edge while sharing one Nexara operating standard." },
        { title: "Build proof people can feel", body: "Show work, flows, scopes, outputs and review loops before making big outcome claims." },
        { title: "Move fast without going vague", body: "Momentum only counts when the offer, owner, timeline and next action are locked." },
        { title: "Ship production-grade or don't ship", body: "Every site, cohort, campaign and AI system should be built for real use — not presentation theater." },
        { title: "Never let the brand go generic", body: "Gen Z can sound sharp and the Firm can sound formal, but both should feel unmistakably Nexara." },
      ],
    },
    trust: {
      manifesto: "Nexara is an incorporated capability firm with three specialist forces: Academy for talent, Digital for market infrastructure, Labs for applied AI. Each goes deep in its own discipline. All three answer to one standard — a named owner, a written scope, a reporting cadence, and clear evidence and data boundaries on every engagement. Three forces, one standard.",
      principles: [
        { title: "Each force owns its discipline", body: "Academy, Digital and Labs are separate specialist lines with their own depth, scopes and decision paths." },
        { title: "One governance standard across all three", body: "Every engagement names an owner, defines deliverables and cadence, and records evidence, handoff and next steps." },
        { title: "Claims tie to a scoped artifact", body: "We connect every claim to a metric, a review process or a documented objective — never an invented number." },
        { title: "Ship what holds in production", body: "Cohorts, websites, campaigns and AI workflows are built to survive past the first launch, not to demo well." },
        { title: "No force outranks another", body: "The gateway changes how the firm presents; it never makes one division read as secondary." },
      ],
    },
  },
  contact: {
    neo: {
      eyebrow: "LET'S BUILD",
      title: "We work with builders. Start here.",
      accent: "info@nexaragroups.com",
      body: "Pick a section. Tell us what you're building. We'll take it from there.",
      primary: "Get started",
    },
    trust: {
      eyebrow: "Project Enquiries",
      title: "A structured engagement starts with one conversation.",
      accent: "info@nexaragroups.com",
      body: "Tell us the force, the city, the audience and the success metric. We come back with a scoped next step and a named owner.",
      primary: "Scope your project",
    },
    channels: [
      { title: "Talent Programmes", section: "academy", body: "Learner count, target roles, city, duration, placement-readiness needs and reporting expectations." },
      { title: "Digital Solutions", section: "marketing", body: "Business category, offer, current website or channels, launch timeline and growth goal." },
      { title: "Product Studio", section: "labs", body: "Business problem, current tools, product users, integrations, risk level and success metric." },
      { title: "Combined engagement", section: "home", body: "When the project needs talent, market presence and systems working together under one owner." },
    ],
    enquiry: {
      title: "Scope your project",
      body: "Work through the planner. When it's done, your mail client opens a formatted request addressed to our intake team — the same checklist we scope every engagement against.",
      label: "Send to info@nexaragroups.com",
      href: "mailto:info@nexaragroups.com",
    },
    checklist: ["Force and city", "Audience or user group", "Timeline and schedule", "Current assets or tools", "Success metric", "Decision-maker contact"],
  },
};
